name: Jira Ticket Linker

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Extract and update Jira tickets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          python - <<EOF
          import re
          import os
          from github import Github

          def extract_jira_tickets(text):
              return re.findall(r'SCRUM-\d+', text)

          def create_jira_section(tickets):
              if not tickets:
                  return ""
              section = "Jira Tickets:\n\n"
              for ticket in tickets:
                  section += f"* [{ticket}](https://deviaco.atlassian.net/browse/{ticket})\n"
              return section + "\n"

          g = Github(os.environ['GITHUB_TOKEN'])
          repo = g.get_repo(os.environ['REPO'])
          pr = repo.get_pull(int(os.environ['PR_NUMBER']))

          # Extract tickets from PR title, branch name, and commit messages
          tickets = set()
          tickets.update(extract_jira_tickets(pr.title))
          tickets.update(extract_jira_tickets(pr.head.ref))
          for commit in pr.get_commits():
              tickets.update(extract_jira_tickets(commit.commit.message))

          # Sort tickets
          sorted_tickets = sorted(list(tickets))

          # Update PR title
          new_title = re.sub(r'\s*SCRUM-\d+', '', pr.title)  # Remove existing tickets from title
          new_title += ' ' + ' '.join(sorted_tickets)

          # Create new PR body
          new_jira_section = create_jira_section(sorted_tickets)
          new_body = new_jira_section + "Original PR Description:\n\n" + (pr.body or "")

          # Update PR
          pr.edit(title=new_title, body=new_body)
          EOF
