# ... (previous parts of the workflow remain the same)

      - name: Extract and update Jira tickets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          python - <<EOF
          import re
          import os
          from github import Github

          def extract_jira_tickets(text):
              return re.findall(r'SCRUM-\d+', text)

          def clean_pr_body(body):
              # Remove everything up to and including the last "Jira Tickets:" section
              pattern = r'^(.*\n)*?Jira Tickets:(\n|.)*?(?=\n\n|\Z)'
              cleaned_body = re.sub(pattern, '', body, flags=re.MULTILINE | re.DOTALL)
              return cleaned_body.strip()

          g = Github(os.environ['GITHUB_TOKEN'])
          repo = g.get_repo(os.environ['REPO'])
          pr = repo.get_pull(int(os.environ['PR_NUMBER']))

          # Extract tickets from PR title, branch name, and commit messages
          tickets = set()
          tickets.update(extract_jira_tickets(pr.title))
          tickets.update(extract_jira_tickets(pr.head.ref))
          for commit in pr.get_commits():
              tickets.update(extract_jira_tickets(commit.commit.message))

          # Sort tickets
          sorted_tickets = sorted(list(tickets))

          # Update PR title
          new_title = re.sub(r'\s*SCRUM-\d+', '', pr.title)  # Remove existing tickets from title
          new_title += ' ' + ' '.join(sorted_tickets)

          # Create new Jira tickets section
          new_jira_section = "Jira Tickets:\n\n"
          for ticket in sorted_tickets:
              new_jira_section += f"* [{ticket}](https://deviaco.atlassian.net/browse/{ticket})\n"
          new_jira_section += "\n"

          # Clean existing body and add new Jira section
          existing_body = pr.body or ""
          cleaned_body = clean_pr_body(existing_body)
          new_body = new_jira_section + cleaned_body

          # Update PR
          pr.edit(title=new_title, body=new_body)
          EOF
